---
title: "sentiment_communi_data"
author: "mwa"
date: "2023-08-14"
output: html_document
---

check "https://github.com/juliasilge/tidytext" for tidy form data
check "https://www.tidytextmining.com/sentiment.html#sentiment" for various sentiment analysis

##get lexicons
```{r}
get_sentiments("afinn")
get_sentiments("bing")
get_sentiments("nrc")
```

##tidy data format
```{r}
library(tidytext)
tidy_communication <- GGcommunicationdataset_mw_062723 %>%
  unnest_tokens(word, text)
```

##remove stop words
```{r}
tidy_communication <- tidy_communication %>%
  anti_join(get_stopwords())
```

##frequent words
```{r}
tidy_communication %>%
  count(word, sort = TRUE) 
```

##sentiment analysis
```{r}
ggsentiment <- tidy_communication %>%
  inner_join(get_sentiments("bing"), by = "word", relationship = "many-to-many") %>% 
  count(sentiment, index = round_whole) %>% 
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>% 
  mutate(sentiment = positive - negative)
ggsentiment
```

##visualize
```{r}
library(ggplot2)
ggplot(ggsentiment, aes(index, sentiment, fill = "blue")) +
  geom_col(show.legend = FALSE)
```
##4games
```{r}
library(tidytext)
tidy_4games <- X4gamesdata_070123 %>%
  unnest_tokens(word, text)
```

##remove stop words
```{r}
tidy_4games <- tidy_4games %>%
  anti_join(get_stopwords())
```

##frequent words
```{r}
tidy_4games %>%
  count(word, sort = TRUE) 
```
##sentiment analysis of 4games
```{r}
games_sentiment <- tidy_4games %>%
  inner_join(get_sentiments("bing"), by = "word", relationship = "many-to-many") %>% 
  count(Game, index = round_db, sentiment) %>% 
  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) %>% 
  mutate(sentiment = positive - negative)
```

##visualization of 4games
```{r}
library(ggplot2)
games_sentiment_cleaned <- na.omit(games_sentiment)
ggplot(games_sentiment_cleaned, aes(index, sentiment, fill = Game)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(vars(Game), ncol = 2, scales = "free_x")
```

##
```{r}
library(dplyr)
games_sentiment_cleaned <- games_sentiment_cleaned %>%
  rename(round_db = index)
```

```{r}
fourgamesdata <- merge(games_sentiment_cleaned, X4gamesdata_070123, by = c("round_db"))
```

```{r}
install.packages("openxlsx")
library(openxlsx)
write.xlsx(fourgamesdata, "fourgamesdata.xlsx")
```
